### ISSUE TITLE
FAIL: generic_agent_test

### ISSUE THREAD

**Issue by OlTwello** [Webhuis/Cfengine-debian#14]
# 
# Starting test: generic_agent_test.c

test_load_masterfiles: Starting test
FAIL: generic_agent_test

I would like to assign this issue to Ted. I will mail the logs to the Debian-team.

**Comment by tzz** [comment]
I looked at the build logs.  Looks like it's choking on `logrotate` which is defined in either `lib/3.5/bundles.cf` for 3.5.x or in `$(sys.local_libdir)/bundles.cf` for 3.6 (which expands to `lib/3.6/bundles.cf`).

Actual error:

```
/usr/local/src/Cfengine-debian/masterfiles/promises.cf:72:30: error: syntax error
  "rotate_promise_summary" usebundle => logrotate("@(def.cfe_log_files)", "1m", "10"),
```

**Comment by Webhuis** [comment]
Discussed in the October 8th hangout. Brian and Ted analyse.

**Comment by bahamat** [comment]
I'm not getting this error anymore while building.
