### ISSUE TITLE
Import masterfiles repo as a submodule or branch

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#2]

**Comment by tzz** [comment]
Take a look at the subtree merge strategy, it's ideal for this.

**Comment by Webhuis** [comment]
OK, next branch. This is in advance of the more definitive master files split Ted told us about.
Where do I find the current (3.5.2) repo?

**Comment by tzz** [comment]
https://github.com/cfengine/masterfiles doesn't have a 3.5.x branch because there hasn't been a 3.5 release using it since it was created (3.5.2 still used the `core.git/masterfiles` directory).  So for now use the `master` branch and eventually there may be a 3.5.2 branch.

**Comment by Webhuis** [comment]
So, I will
1. Create a branch masterfiles of off orig
2. Remove everything but masterfiles from the masterfiles branch
3.5.2 remains intact
OK?

**Comment by Webhuis** [comment]
Three branches available now.
orig
debian with debian directory
masterfiles with masterfiles directory
