### ISSUE TITLE
tests/acceptance/00_basics/01_compiler/800.cf FAIL

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#24]
This tests `$(sys.flavor)`.

Jessie output: 

```
$ sudo cf-agent -K -f ./tests/acceptance/00_basics/01_compiler/800.cf -D AUTO,DEBUG     
2013-10-13T01:30:10-0700   notice: R: Compared debian_jessie to debian_jessie/sid
2013-10-13T01:30:10-0700   notice: R: ./tests/acceptance/00_basics/01_compiler/800.cf FAIL
```

wheezy output:

```
$ sudo cf-agent -K -f ./tests/acceptance/00_basics/01_compiler/800.cf -D AUTO,DEBUG     
2013-10-13T01:33:02-0700   notice: R: Compared debian_7 to debian_7
2013-10-13T01:33:02-0700   notice: R: ./tests/acceptance/00_basics/01_compiler/800.cf Pass
```

This test may resolve itself when `/etc/issue` is updated to a version number for jessie release. However, with the current acceptance test it can never pass on testing or unstable. This needs to pass on testing/unstable otherwise it will always fail Debian builds on the official build system.

**Comment by basvandervlies** [comment]
what is /etc/debian_version and /dev/isssue?

On 13 okt. 2013, at 10:36, Brian Bennett notifications@github.com wrote:

> This tests $(sys.flavor).
> 
> Jessie output:
> 
> $ sudo cf-agent -K -f ./tests/acceptance/00_basics/01_compiler/800.cf -D AUTO,DEBUG  
> 2013-10-13T01:30:10-0700   notice: R: Compared debian_jessie to debian_jessie/sid
> 2013-10-13T01:30:10-0700   notice: R: ./tests/acceptance/00_basics/01_compiler/800.cf FAIL
> 
> wheezy output:
> 
> $ sudo cf-agent -K -f ./tests/acceptance/00_basics/01_compiler/800.cf -D AUTO,DEBUG  
> 2013-10-13T01:33:02-0700   notice: R: Compared debian_7 to debian_7
> 2013-10-13T01:33:02-0700   notice: R: ./tests/acceptance/00_basics/01_compiler/800.cf Pass
> 
> This test may resolve itself when /etc/issue is updated to a version number for jessie release. However, with the current acceptance test it can never pass on testing or unstable. This needs to pass on testing/unstable otherwise it will always fail Debian builds on the official build system.
> 
> —
> Reply to this email directly or view it on GitHub.

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by basvandervlies** [comment]
can you also tell which debian hard classes are detected? Currently i do not have a jessie system

On 13 okt. 2013, at 11:38, Bas van der Vlies bas.vandervlies@surfsara.nl
 wrote:

> what is /etc/debian_version and /dev/isssue?
> 
> On 13 okt. 2013, at 10:36, Brian Bennett notifications@github.com wrote:
> 
> > This tests $(sys.flavor).
> > 
> > Jessie output:
> > 
> > $ sudo cf-agent -K -f ./tests/acceptance/00_basics/01_compiler/800.cf -D AUTO,DEBUG  
> > 2013-10-13T01:30:10-0700   notice: R: Compared debian_jessie to debian_jessie/sid
> > 2013-10-13T01:30:10-0700   notice: R: ./tests/acceptance/00_basics/01_compiler/800.cf FAIL
> > 
> > wheezy output:
> > 
> > $ sudo cf-agent -K -f ./tests/acceptance/00_basics/01_compiler/800.cf -D AUTO,DEBUG  
> > 2013-10-13T01:33:02-0700   notice: R: Compared debian_7 to debian_7
> > 2013-10-13T01:33:02-0700   notice: R: ./tests/acceptance/00_basics/01_compiler/800.cf Pass
> > 
> > This test may resolve itself when /etc/issue is updated to a version number for jessie release. However, with the current acceptance test it can never pass on testing or unstable. This needs to pass on testing/unstable otherwise it will always fail Debian builds on the official build system.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> ---
> 
> SURFsara has a new telephone number: +31 20 800 1300. 
> 
> Bas van der Vlies
> | Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
> | T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by bahamat** [comment]
`/etc/issue` is the standard header for login prompts. 

`/etc/debian_version` is a human readable file that is explicitly used to note the version of Debian the system is running.

Cfengine uses these to determine some hard classes.

**Comment by basvandervlies** [comment]
Brian i know what the files for. I want just want to know what the content is ;-).   I suspect that the hard class:
- debian_testing of debian_unstable is set.  (cf-promises -v)

Then we can rewrite the acceptance test to use another compare test for sys.flavor. 

On 13 okt. 2013, at 11:41, Brian Bennett notifications@github.com wrote:

> /etc/issue is the standard header for login prompts.
> 
> /etc/debian_version is a human readable file that is explicitly used to note the version of Debian the system is running.
> 
> Cfengine uses these to determine some hard classes.
> 
> —
> Reply to this email directly or view it on GitHub.

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by bahamat** [comment]
Here's the list of classes I have on Jessie:

```
any
cfengine
cfengine_3
cfengine_3_5
cfengine_3_5_2
cfengine_in_high
common
community_edition
compiled_on_linux_gnu
debian
debian_jessie
have_aptitude
inform_mode
jessie
linux
linux_3_10_3_amd64
linux_x86_64
linux_x86_64_3_10_3_amd64
linux_x86_64_3_10_3_amd64__1_SMP_Debian_3_10_11_1__2013_09_10_
localhost
net
verbose_mode
x86_64
```

I removed classes unique to my system (md5 hash, interfaces, cf-monitor derived, etc).

Notably missing are the Debian version number classes. Wheezy has the following:

```
debian
debian_7
debian_7_1
debian_7__n__l
```

These numbers come from `/etc/issue` and `/etc/debian_version`.

Note the spurious `debian_7__n__l` hard class which should not be defined. It's an artifact of misreading `/etc/issue`. I'm not worried about the spurious class though. I'll file that with upstream later.

**Comment by bahamat** [comment]
I thought it was funny that you asked ;-)

`/etc/issue`:

```
Debian GNU/Linux jessie/sid \n \l

```

`/etc/issue` has an extra blank line at the end.

`/etc/debian_version`:

```
jessie/sid
```

**Comment by basvandervlies** [comment]
Thanks.  CFengine must handle the debian testing and unstable release or just set: 
- debian_sid
- debian_testing

So we can use that hard classes in the acceptance tests. Else we encounter this problem with every new debian release.

On 13 okt. 2013, at 11:53, Brian Bennett notifications@github.com
 wrote:

> I thought it was funny that you asked ;-)
> 
> /etc/issue:
> 
> Debian GNU/Linux jessie/sid \n \l
> 
> This file has an extra blank line at the end.
> 
> /etc/debian_version:
> 
> jessie/sid
> 
> —
> Reply to this email directly or view it on GitHub.

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by bahamat** [comment]
It sets debian_jessie on jessie. I believe that on unstable it sets debian_unstable (but I don't have one to verify at the moment).

At any rate, the test policy could be "fixed" by appending `cut -d/ -f1` to the pipe. I think it's ok to do that for Jessie, but I don't know if that's really the best way to fix it. I'd like input from someone from cfengine (git blame shows Volker for that line) on how best to fix it.

**Comment by basvandervlies** [comment]
On 13 okt. 2013, at 12:08, Brian Bennett notifications@github.com wrote:

> It sets debian_jessie on jessie. I believe that on unstable it sets debian_unstable (but I don't have one to verify at the moment).
> 
> At any rate, the test policy could be "fixed" by appending cut -d/ -f1 to the pipe. I think it's ok to do that for Jessie, but I don't know if that's really the best way to fix it. I'd like input from someone from cfengine (git blame shows Volker for that line) on how best to fix it.

If i remember correctly CFengine used to use the command `lsb_release` to determine hard classes for a machine. This command on jessie display the right info:
- lsb_release -a 
  {{{
  Distributor ID: Debian
  Description:    Debian GNU/Linux testing (jessie)
  Release:    testing
  Codename:   jessie
  }}}

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by bahamat** [comment]
Cfengine is likely doing the right thing, but the test case checks against `/etc/issue`.
Perhaps modifying the test case to use `lsb_release` is the right thing to do.

**Comment by bahamat** [comment]
Although, `lsb-release` is not an essential package and may not always exist.

**Comment by basvandervlies** [comment]
On 15 okt. 2013, at 00:59, Brian Bennett notifications@github.com wrote:

> Cfengine is likely doing the right thing, but the test case checks against /etc/issue.
> Perhaps modifying the test case to use lsb_release is the right thing to do.

Brian just a note cfengine is not doing the rugjt thing it could define another debian class when parsing /etc/debian_version:
- debian_sid

This can always be used for debian systems that are not yet stable. Stable debian versions have a version number:  
- major.minor.patch  
- maybe also declare: debian_stable

Testinfg/Unstable have the following name schema::
- jessie/sid

So the code in sys info.c can be adjusted to declare the class debian_sid.

For know there is no way to detect if we have a debian stable, testing or unstable

In cfengine 3.0.5 they still used: lsb_release to set hard classes, but CFengine team has removed the code.

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by basvandervlies** [comment]
Each time a stumble in this error when building for jessie. So what is the plan?:
- delete the test.
- patch it

**Comment by bahamat** [comment]
Preferably fix it upstream and patch it with the same fix.

Since Jessie's freeze is over a year away we should have a new version of cfengine by then and we should be able to have considerably fewer patches.

**Comment by basvandervlies** [comment]
Brian,

 With the next release after jessie we have the same problem debian with version numbers: consider ‘stable’ and testing and unstable releases.  For now i am  in favor just rm the test in debian/rules  and if there is fix in upstream we can apply it. It is all about defining the proper hard classes. They are solving it with the “inventory” framework.

regards
On 29 okt. 2013, at 15:30, Brian Bennett notifications@github.com wrote:

> Preferably fix it upstream and patch it with the same fix.
> 
> Since Jessie's freeze is over a year away we should have a new version of cfengine by then and we should be able to have considerably fewer patches.
> 
> —
> Reply to this email directly or view it on GitHub.

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by tzz** [comment]
The inventory framework is in place, with a LSB module.  What do I need to do to make the test pass?

**Comment by bahamat** [comment]
Backport that fix into this repo, as a quilt patch.

**Comment by basvandervlies** [comment]
@tzz the faling test is all about that the stable debian version uses numbers and the other names in /etc/issue.
- wheezy (stable) --> debian_7  (sys.flavor)
- jessie (testng) -> debian_jessie  (sys.flavor)

Now the test fails, due to: /bin/grep Debian.*GNU /etc/issue | /usr/bin/cut -d' ' -f3 | cut -d. -f1
- wheezy --> 7
- jessie    --> jessie/sid != sys.flavor --> FAIL

When jessie becomes stable it will get a number. But then this test will fail on the next testing release.

**Comment by bahamat** [comment]
On Jessie, currently `sys.flavor` becomes `debian_jessie`. I think that's ok (or at least not terrible). The problem is that the test parses and chops `/etc/issue`, and it _thinks_ the `sys.flavor` should be `debian_jessie_sid`. So it's really the test that's doing the wrong thing.

The test can be fixed by adding another cut at the end to chop off the sid part, but I'm not sure that's the best way to solve it. In particular, I'm not sure what happens on sid.

Secondly, it looks like Mark has stated on the list that cfengine used to use lsb but it was too slow and so was removed. So there's that.

**Comment by tzz** [comment]
Can the test be fixed to use `lsb_release` if it's present and fall back to `/etc/issue` parsing?  That would make the most sense to me.

LSB is OK to use for testing, at least.  Also there's `lsb.cf` in the new masterfiles inventory framework, which will be available in 3.6.

**Comment by ediosyncratic** [comment]
/etc/debian_version sounds like it's actually the better solution here !  I was unaware of that when fixing this - I guess I'm the only developer on staff that uses testing, so I ran into it independently, unaware of this thread.  I'll fix this up in a later commit, now that I know about it - thanks @basvandervlies for linking here from my code review !

**Comment by bahamat** [comment]
Can you make sure to link the commit here as well? I want to make sure it gets included in the debian package.

Thanks Edward.

## 

Brian

**Comment by ediosyncratic** [comment]
bahamat: here's my (somewhat belated) pull request for the further refinement of the test:
https://github.com/cfengine/core/pull/1213

My original commit is eaaf3ad222db81089031bd306dcf8df342ec1ef9 on cfengine/core's master and fixes your problem; this later pull request is just a refinement to _how_ it's fixed ...
