### ISSUE TITLE
Pull request 1010 from core needs to be merged in with quilt

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#25]
See https://github.com/cfengine/core/pull/1010

**Comment by bahamat** [comment]
After building with this fix I have a usable `.deb`

**Comment by basvandervlies** [comment]
congrats!. I have just updated my branch with your quilt patch for strftime  that you submitted

On 13 okt. 2013, at 11:57, Brian Bennett notifications@github.com
 wrote:

> After building with this fix I have a usable .deb
> 
> —
> Reply to this email directly or view it on GitHub.

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by bahamat** [comment]
This is resolved.
