### ISSUE TITLE
debian/rules uses wrong configure option

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#26]
In Bas' create-deb-package branch there is an incorrect option `--with-acl`. The correct option is `--with-libacl`.

**Comment by basvandervlies** [comment]
Thanks will fix it

On 13 okt. 2013, at 11:31, Brian Bennett notifications@github.com
 wrote:

> In Bas' create-deb-package branch there is an incorrect option --with-acl. The correct option is --with-libacl.
> 
> —
> Reply to this email directly or view it on GitHub.

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by bahamat** [comment]
Initially I saw a warning saying that `--with-acl` was an invalid option. Trying with `--with-libacl` fails to find `libacl`. Removing the option entirely lets cfengine find the correct path automatically.
