### ISSUE TITLE
Build dependencies

### ISSUE THREAD

**Issue by Webhuis** [Webhuis/Cfengine-debian#3]
We are dealing with build dependencies. We should have a clear picture of the dependencies that exist.

**Comment by basvandervlies** [comment]
On 3 okt. 2013, at 10:54, Webhuis notifications@github.com
 wrote:

> We are dealing with build dependencies. We should have a clear picture of the dependencies that exist.
> 
> I just did some dependencies on my own debian package. I just submitted a pull request< see:
> - https://github.com/Webhuis/Cfengine-debian/pull/6/

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by Webhuis** [comment]
OK, point taken. I cannot assign the issue to you right now, but we will pick this up tomorrow.

**Comment by Webhuis** [comment]
Solved by pull requests #6 and #19.
