### ISSUE TITLE
Lintian messages

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#37]
This issue will track overall progress on Lintian messages.

Current output:

```
N: Processing binary package cfengine3 (version 3.5.2-1+nmu1, arch amd64) ...
W: cfengine3: package-name-doesnt-match-sonames libpromises3
I: cfengine3: spelling-error-in-binary usr/lib/libpromises.so.3.0.5 deamon daemon
I: cfengine3: spelling-error-in-binary usr/lib/libpromises.so.3.0.5 Commerical Commercial
I: cfengine3: spelling-error-in-binary usr/lib/libpromises.so.3.0.5 avaiable available
W: cfengine3: hardening-no-relro usr/lib/libpromises.so.3.0.5
W: cfengine3: hardening-no-fortify-functions usr/lib/libpromises.so.3.0.5
W: cfengine3: hardening-no-relro usr/sbin/cf-agent
W: cfengine3: hardening-no-fortify-functions usr/sbin/cf-agent
W: cfengine3: hardening-no-relro usr/sbin/cf-execd
W: cfengine3: hardening-no-fortify-functions usr/sbin/cf-execd
W: cfengine3: hardening-no-relro usr/sbin/cf-key
W: cfengine3: hardening-no-fortify-functions usr/sbin/cf-key
W: cfengine3: hardening-no-relro usr/sbin/cf-monitord
W: cfengine3: hardening-no-fortify-functions usr/sbin/cf-monitord
W: cfengine3: hardening-no-relro usr/sbin/cf-promises
I: cfengine3: spelling-error-in-binary usr/sbin/cf-runagent overriden overridden
W: cfengine3: hardening-no-relro usr/sbin/cf-runagent
W: cfengine3: hardening-no-fortify-functions usr/sbin/cf-runagent
W: cfengine3: hardening-no-relro usr/sbin/cf-serverd
W: cfengine3: hardening-no-fortify-functions usr/sbin/cf-serverd
W: cfengine3: hardening-no-relro usr/sbin/rpmvercmp
W: cfengine3: binary-without-manpage usr/sbin/cf-agent
W: cfengine3: binary-without-manpage usr/sbin/cf-execd
W: cfengine3: binary-without-manpage usr/sbin/cf-key
W: cfengine3: binary-without-manpage usr/sbin/cf-monitord
W: cfengine3: binary-without-manpage usr/sbin/cf-promises
W: cfengine3: binary-without-manpage usr/sbin/cf-runagent
W: cfengine3: binary-without-manpage usr/sbin/cf-serverd
W: cfengine3: binary-without-manpage usr/sbin/rpmvercmp
W: cfengine3: non-dev-pkg-with-shlib-symlink usr/lib/libpromises.so.3.0.5 usr/lib/libpromises.so
I: cfengine3: no-symbols-control-file usr/lib/libpromises.so.3.0.5
N: 1 tag overridden (1 info)
```

**Comment by bahamat** [comment]
Commit a2b79ae cleaned up a lot of these messages.

Current lintian status:

```
N: Processing binary package cfengine3 (version 3.5.2-1+nmu1, arch amd64) ...
W: cfengine3: package-name-doesnt-match-sonames libpromises3
W: cfengine3: binary-without-manpage usr/sbin/cf-agent
W: cfengine3: binary-without-manpage usr/sbin/cf-execd
W: cfengine3: binary-without-manpage usr/sbin/cf-key
W: cfengine3: binary-without-manpage usr/sbin/cf-monitord
W: cfengine3: binary-without-manpage usr/sbin/cf-promises
W: cfengine3: binary-without-manpage usr/sbin/cf-runagent
W: cfengine3: binary-without-manpage usr/sbin/cf-serverd
W: cfengine3: binary-without-manpage usr/sbin/rpmvercmp
W: cfengine3: non-dev-pkg-with-shlib-symlink usr/lib/libpromises.so.3.0.5 usr/lib/libpromises.so
I: cfengine3: no-symbols-control-file usr/lib/libpromises.so.3.0.5
N: 1 tag overridden (1 info)
```

**Comment by bahamat** [comment]
Current lintian status:

```
N: Processing binary package cfengine3 (version 3.5.2-1+nmu1, arch amd64) ...
W: cfengine3: package-name-doesnt-match-sonames libpromises3
W: cfengine3: binary-without-manpage usr/sbin/cf-agent
W: cfengine3: binary-without-manpage usr/sbin/cf-execd
W: cfengine3: binary-without-manpage usr/sbin/cf-key
W: cfengine3: binary-without-manpage usr/sbin/cf-monitord
W: cfengine3: binary-without-manpage usr/sbin/cf-promises
W: cfengine3: binary-without-manpage usr/sbin/cf-runagent
W: cfengine3: binary-without-manpage usr/sbin/cf-serverd
W: cfengine3: binary-without-manpage usr/sbin/rpmvercmp
W: cfengine3: non-dev-pkg-with-shlib-symlink usr/lib/libpromises.so.3.0.5 usr/lib/libpromises.so
N: 1 tag overridden (1 info)
```

**Comment by tzz** [comment]
Can I assume the lintian errors are due to https://github.com/Webhuis/Cfengine-debian/issues/40 ?

I don't think we can fix the soname, `libpromises` is pretty fundamental to CFEngine.

The last warning seems weird.  Isn't that how you're supposed to install libraries?  Or am I misunderstanding something?

**Comment by bahamat** [comment]
I think it's important to include the man pages.

For the other two, I think Debian's recomendation is that cfengine3 should be split into two separate packages. One package would be `libpromises`, and contain only the `libpromises` stuff. The second would be `cfengine3` which depends on `libpomises`.

How crazy would it be to split it like that? If it's trivial, or very easy then I guess, why not? But if it's anything more than trivial or very easy then I would rather just override the warnings and ignore it.

**Comment by bahamat** [comment]
Also, for reference, Lintian has (at least) four types of messages. Notice, info, warning and errors.

We've never had any lintian _errors_, they've always been at warning or below.

**Comment by basvandervlies** [comment]
@tzz, @bahamat we can also switch to static binaries then this warning will disappear.  But then we can not use the cfe-profiler.

**Comment by bahamat** [comment]
I'd like to have the option of using the profiler. There are lots of other debian packages that squelch or do nothing about each of these messages, so I'm fine doing that as well, unless there's strong objection raised by Debian.

**Comment by basvandervlies** [comment]
@bahamat +1

**Comment by tzz** [comment]
Splitting off libpromises for the sake of a warning is IMO not worth the effort, so I'll go with @bahamat

**Comment by bahamat** [comment]
In that case I'm assigning to myself and I'll configure a lintian override for those two messages.

**Comment by bahamat** [comment]
I've now merged in a new override that takes care of both of the libpromises messages. The last thing is the man pages then it'll be done.

Ted had a good idea for creating a new acceptance test that produces the man pages. I'll use that as a last resort if I can't do it directly in `debian/rules`.

**Comment by tzz** [comment]
I commented in https://github.com/cfengine/core/pull/1059 and https://github.com/cfengine/core/pull/1037 as well because they seem to be blocking each other to block the @basvandervlies  patch.

**Comment by bahamat** [comment]
Since the only thing left is the missing man pages #40 specifically addresses that, I think this issue can be considered closed.
