### ISSUE TITLE
Spelling mistakes exposed by lintian

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#38]
See https://github.com/cfengine/core/pull/1024

In total, >600 files contain spelling mistakes. This will be kind of a pain to patch with quilt.

**Comment by basvandervlies** [comment]
@bahamat see pull request #39. You are done ;-)

**Comment by bahamat** [comment]
I fixed a few more in the patch rebase, which takes care of all of them. Thanks Bas.
