### ISSUE TITLE
Compile options

### ISSUE THREAD

**Issue by Webhuis** [Webhuis/Cfengine-debian#4]
The current setup contains faulty and missing compile options.

**Comment by Webhuis** [comment]
Invalid compile options removed:
--without-nova \
--without-constellation

Ccompile option added:
 --with-mysql to yes

Indentification off additional compile options needed.

**Comment by basvandervlies** [comment]
just send a pull request #17 which enable some optional pakcages

**Comment by Webhuis** [comment]
Options added in pull request #17
