### ISSUE TITLE
Man pages missing

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#40]
The man pages in community edition are in `/var/cfengine/share/man/man8/`.

I don't know yet if they're in the package and not in the right place, or missing entirely. I wanted to get this in while it was on my mind.

**Comment by basvandervlies** [comment]
Just a observation in this repository there is no `docs` directory. So that is why we can not install them.

**Comment by tzz** [comment]
What can I do to help here?

**Comment by bahamat** [comment]
The best thing would be for the man pages to be included with the tarball form cfengine. Do you know why they're missing?

**Comment by tzz** [comment]
Oops, wrong button, sorry

**Comment by tzz** [comment]
IIRC the man pages are supposed to be in the package, but don't know about the tarball.  I think they can be generated from source, either way.

@nickanderson @vohi @cduclos can you comment please?

**Comment by basvandervlies** [comment]
In the 3.5.x and master branch there is the directory:
- doc/manpages

```
bas@r7n16:/var/tmp/bas/core/docs/manpages$ ls        
cf-agent.8  cf-execd.8  cf-key.8  cf-monitord.8  cf-promises.8  cf-runagent.8  cf-serverd.8  Makefile  Makefile.am  Makefile.in
```

**Comment by bahamat** [comment]
Debian imports from the tar all though, not the upstream repo.

**Comment by basvandervlies** [comment]
@bahamat i know we fetch the tarball.  I assume that the generation of the tarball goes wrong and does not include the docs directory.

**Comment by vohi** [comment]
The man pages for the binaries are generated by the binaries themselves, via (undocumented) -M command line parameter. There are no man-pages checked into the repository (https://github.com/cfengine/core/tree/master/docs/manpages).

They can't be in the tar ball for that reason, because we don't compile the binaries before we generate the tar ball. There's https://cfengine.com/dev/issues/2989 as a known issue in our own packages.

**Comment by bahamat** [comment]
Ok, that makes a bit more sense. We can add a build step that generates and saves them.

**Comment by tzz** [comment]
Cool, now it makes sense, thanks @vohi

**Comment by bahamat** [comment]
Ted suggested using an acceptance test to create the man pages because the tests already know how to execute the binaries properly.

**Comment by bahamat** [comment]
This patch successfully produces man pages, although I don't think this is the best approach.

Any suggestions on improving this?

```
diff --git a/debian/rules b/debian/rules
index 10086c9..cd1934b 100755
--- a/debian/rules
+++ b/debian/rules
@@ -59,3 +59,11 @@ override_dh_install:

   /bin/rmdir $(CURDIR)/debian/cfengine3/var/lib/cfengine3/inputs
   /bin/rm $(CURDIR)/debian/cfengine3/usr/lib/*.la
+  /bin/mkdir -p $(CURDIR)/debian/cfengine3/usr/share/man/man8/
+  LD_LIBRARY_PATH=$(CURDIR)/debian/cfengine3/usr/lib $(CURDIR)/debian/cfengine3/usr/sbin/cf-agent -M > $(CURDIR)/debian/cfengine3/usr/share/man/man8/cf-agent.8
+  LD_LIBRARY_PATH=$(CURDIR)/debian/cfengine3/usr/lib $(CURDIR)/debian/cfengine3/usr/sbin/cf-execd -M > $(CURDIR)/debian/cfengine3/usr/share/man/man8/cf-execd.8
+  LD_LIBRARY_PATH=$(CURDIR)/debian/cfengine3/usr/lib $(CURDIR)/debian/cfengine3/usr/sbin/cf-key -M > $(CURDIR)/debian/cfengine3/usr/share/man/man8/cf-key.8
+  LD_LIBRARY_PATH=$(CURDIR)/debian/cfengine3/usr/lib $(CURDIR)/debian/cfengine3/usr/sbin/cf-monitord -M > $(CURDIR)/debian/cfengine3/usr/share/man/man8/cf-monitord.8
+  LD_LIBRARY_PATH=$(CURDIR)/debian/cfengine3/usr/lib $(CURDIR)/debian/cfengine3/usr/sbin/cf-promises -M > $(CURDIR)/debian/cfengine3/usr/share/man/man8/cf-promises.8
+  LD_LIBRARY_PATH=$(CURDIR)/debian/cfengine3/usr/lib $(CURDIR)/debian/cfengine3/usr/sbin/cf-runagent -M > $(CURDIR)/debian/cfengine3/usr/share/man/man8/cf-runagent.8
+  LD_LIBRARY_PATH=$(CURDIR)/debian/cfengine3/usr/lib $(CURDIR)/debian/cfengine3/usr/sbin/cf-serverd -M > $(CURDIR)/debian/cfengine3/usr/share/man/man8/cf-serverd.8
```

There's still no man page for `rpmvercmp`, but I'm overriding that.

**Comment by basvandervlies** [comment]
@bahamat maybe this:

```
    for p in cf-agent cf-key cf-promises cf-runagent cf-execd cf-serverd cf-monitord; \
    do \
        $(CURDIR)/$$p/$$p -M > $(CURDIR)/debian/cfengine3/usr/share/man/man8/$$p.8 ;\
    done
```

I tested this and it works.

**Comment by bahamat** [comment]
Excellent, thanks.  I'll use that.

**Comment by basvandervlies** [comment]
I have issued sn pull request https://github.com/Webhuis/Cfengine-debian/pull/51

**Comment by basvandervlies** [comment]
and applied
