### ISSUE TITLE
Fix virtual interface detection

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#46]
This one affects me directly, so I want to make sure it gets included.

The problem is that cfengine ignores some interfaces if it detects that they are virtual. I have a number of virtual machines in which **all** interfaces are detected as virtual and get ignored.

The upstream bug is https://cfengine.com/dev/issues/3420

There's a patch included in the bug that should address the issue, but may need to be ported in.

**Comment by tzz** [comment]
OK with me.

**Comment by bahamat** [comment]
The fix for this will be included in 3.7.

Pull request is here: https://github.com/cfengine/core/pull/1819

This issue will not be cherry picked into 3.6. If we import it then we'll have different behavior on Debian than on other platforms. I'm therefore inclined to close this issue without back porting.
