### ISSUE TITLE
process select stime_range bug in calculation epoch time 

### ISSUE THREAD

**Issue by basvandervlies** [Webhuis/Cfengine-debian#47]
See issue: 
- https://cfengine.com/dev/issues/2921

The pull request is accepted in the master branch, but no applied to 3.5.2 or 3.5.X branch. This one effects me.

**Comment by tzz** [comment]
I commented in the Redmine ticket to @vohi for merging into 3.5.x

**Comment by basvandervlies** [comment]
it has been backported to 3.5.x. thanks

**Comment by basvandervlies** [comment]
i close it it is in 3.5.x and 3.6
