### ISSUE TITLE
Need to build and test on sid

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#48]

**Comment by ballock** [comment]
I believe this needs to be extended to backports (wheezy) and Ubuntu distros. Also, we would benefit from having an automated build system for latest upstream Git release.

I went through automatic CI and build systems that came up to my head (hosted):
1. build.opensuse.org (opensuse build system) - should work, but its .deb support functions look like being a hack.
2. launchpad.net - only builds for Ubuntu, may require the code to be in bizzare bzr repository.
3. travis-ci.org - only builds on Ubuntu 12.04 amd64 machines

So, what's left is something that would need to be set up on an internal machine:
1. Jenkins + pbuilder

Please comment if you come up with some other hosted or internal tools we could use for CI and build.

**Comment by tzz** [comment]
CFEngine's internal Jenkins service could be hooked to test the Debian package, if the community members are OK with that dependency.  @Webhuis @bahamat let me know if I should request it.

**Comment by jooooooon** [comment]
On 12/05/14 16:45, Ted Zlatanov wrote:

> CFEngine's internal Jenkins service could be hooked to test the Debian 
> package, if the community members are OK with that dependency. 
> @Webhuis https://github.com/Webhuis @bahamat 
> https://github.com/bahamat let me know if I should request it.

I'd rather a Jenkins instance we could actually access, to be able to 
analyse build failures, etc. Would that be possible?

Jonathan

**Comment by tzz** [comment]
I don't think it's possible, the CFEngine internal Jenkins setup is too sensitive.

**Comment by bahamat** [comment]
I can host one, but it would be IPv6 only.

## 

Brian

**Comment by ballock** [comment]
I think my email did not get to ihe issues list here; whatever.

So we've got 2 ipv6-only servers (I mentioned I have one). Anyone has experience if Jenkins can be run on a public interface without security concerns?

**Comment by tzz** [comment]
I don't know anyone running Jenkins in the open.  Maybe a VPN would be a good access filter?

**Comment by jooooooon** [comment]
There are several public installations I know of, most notably https://builds.apache.org. 

But that comment reminded me of CloudBees that are a "Jenkins as a service" company and they offer free Jenkins instances to open source projects: http://www.cloudbees.com/foss/index.cb

**Comment by ballock** [comment]
I had a look at build.apache.org and it's only available for projects related to the Apache Foundation.

Cloudbees look very interesting, but I'm not the type of guy that would be screaming for having built my software on a public service of Cloudbees. I also have some security problems with that one, as for the pbuilder service, I'd need to enter both the public and private key to publish the packages to a PPA.

For now I installed a Jenkins instance on my IPv6-only server and will try to set up pbuilder in that.

**Comment by ballock** [comment]
I set up a puilder environment to build the packages. Then started configuring a promising "Debian Package Builder" plugin for Jenkins.

It turns out that  doesn't use pbuilder, but builds on the Jenkins host directly. That means I need to have a Jenkins slave per distro/architecture, so I needed to change my toys.

Currently I'm planning to use the Docker plugin for Jenkins to spawn Jenkins slaves in each of the distro/architectures.

Btw, I have a imx53qsb, I guess I could use that for building armhf and armel binary packages.

**Comment by ballock** [comment]
I managed to set up a build environment based on Jenkins-debian-glue. It is available via IPv6:
http://osuosl.ballock.random.fi:8080

Currently, none of the builds were successful, I will be reporting/diagnosing that separately.

I was thinking about opening access to the server based on Github authentication in Jenkins, but that assumes we have a Github group, which we don't AFAIK. So I am proposing to set up a group in Github, say cfengine-debian, move our main repository in there, grant the team push access and map the users to Jenkins to perform build-related changes. What do you think?

**Comment by Webhuis** [comment]
Dear Ballock,

> I managed to set up a build environment based on Jenkins-debian-glue. It
> is available via IPv6:
> http://osuosl.ballock.random.fi:8080
> 
> Currently, none of the builds were successful, I will be
> reporting/diagnosing that separately.
> 
> I was thinking about opening access to the server based on Github
> authentication in Jenkins, but that assumes we have a Github group, which
> we don't AFAIK. So I am proposing to set up a group in Github, say
> cfengine-debian, move our main repository in there, grant the team push
> access and map the users to Jenkins to perform build-related changes. What
> do you think?

How about a hangout on this one?

Say Tuesday 17:00 CEST / 8 AM PDT.

Met vriendelijke groet,
Martin.

+13107732970
+31651567029

**Comment by ballock** [comment]
Can do, but 17 CEST is a little to early, I'm still working at the time.
Something between 18-20 and 22-23 CEST are ok.

Cheers,
Ballock

2014-05-30 11:59 GMT+02:00 Webhuis notifications@github.com:

**Comment by ballock** [comment]
My CI setup for package build is now available through IPv4 too.

http://ci.tokarscy.com

Jenkins master runs on my family's domain and VPS, and accesses slaves through IPv6.

It also publishes the built packages (once all the builds are successful) to:

http://ci.tokarscy.com/deb $distribution main

**Comment by bahamat** [comment]
I now have a sid build system. I'll be able to report any build failures there.
