### ISSUE TITLE
Reconcile datadir issue with core

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#49]
The way we fixed `datadir` is not acceptable to cfengine/core. We need to reconcile with them.

**Comment by basvandervlies** [comment]
My reply has vanished ;-(.  In the current behavior we can not choose the destination folder. The options are:
- $(exec_prefix)/share (default and also the default for configure)
- $(exec_prefix/share/cfengine  (--enable-fhs)

CFengine has add a new variable to configure (projdatadir) that does the same as the configure `--datadir` 
option.  What i have done is removed the `projdatadir` and  enabled the `--datadir` again.  Due this change the `--enable-fhs` option has changed for data directory.  I can easily add a statement that restores its behavior. Maybe we must also add another option: `--enable-cfengine` that sets all the path to CFengine company policy.

Debian and other distro;s will benefit if the data directory is configurable. That is the beauty of configure that it easy to specify locations. Now the `-docdir`` is accepted and`--datadir``  is rejected.  Looks like half working configure.

I have asked some question about CFengine decisions on the mailinglist:
- https://groups.google.com/forum/#!searchin/help-cfengine/configure/help-cfengine/vUwBxN9D-7A/16xiQQNy748J

It would be nice to know the reason behind the decisions.

**Comment by Webhuis** [comment]
Dear Bas,

> I have asked some question about CFengine decisions on the mailinglist:
>  *
> https://groups.google.com/forum/#!searchin/help-cfengine/configure/help-cfengine/vUwBxN9D-7A/16xiQQNy748J
> 
> It would be nice to know the reason behind the decisions.

May be we should forward this to the development team in Oslo.

We are putting a lot of effort in this project and it is to the benifit of
CFEngine. What you offer is some sort of an holy grail when it comes to
efficiently packaging CFEngine for all major distributions. I feel it
should be honoured.

Met vriendelijke groet,
Martin.

+31651567029

**Comment by basvandervlies** [comment]
To easliy follow the discussion: 
- https://github.com/cfengine/core/pull/1059

**Comment by basvandervlies** [comment]
Have opened an issue:
- https://cfengine.com/dev/issues/4078

**Comment by basvandervlies** [comment]
Cab be closed it is merge in 3.6 ;-) Thanks to Kristian!
