### ISSUE TITLE
Directory relocations

### ISSUE THREAD

**Issue by bahamat** [Webhuis/Cfengine-debian#53]
Legacy debian cfengine packages have `$(sys.workdir)/inputs` symlinked to `/etc/cfengine`.

This needs to changed so that `/etc/cfengine` is a symlink to `$(sys.workdir)/masterfiles` Instead.

Todo:
- script to perform migration
- debconf dialogs for user

**Comment by thkoch2001** [comment]
It may be worth considering the popcon value of cfengine in Debian: http://qa.debian.org/popcon-graph.php?packages=cfengine3

Depending on how complicate the upgrade is, one might just put a note in the NEWS file and leave it to the potentially 50 users to do the necessary changes.

**Comment by bahamat** [comment]
Given that where cfengine is used, it's used on potentially very _large_ installations. A single vote may represent hundres or thousands of installations. And the typical cfengine user is less inclined to use popcon. Plus, this change has the potential to bring down entire data centers with one feel swoop.

The migration procedure as far as disk files are concerned will be very easy. What we can't account for is policy files that depend on the deprecated locations. For people with simple set ups migration should be very smooth. For complex set ups the user can opt for manual reconfiguration.

So the dialog should present what is being changed, and briefly why. Afterward there should be buttons that say "Fix it for me" and "I will fix it myself". The "Fix it for me" button runs the script, while "I will fix it myself" will skip the script and continue.

**Comment by bahamat** [comment]
This is now moot since Jessie has shipped.
