### ISSUE TITLE
Systemd init script

### ISSUE THREAD

**Issue by ballock** [Webhuis/Cfengine-debian#54]
As it was decided by both Debian and Ubuntu to switch to Systemd init, we need a systemd-compliant init script.

**Comment by tzz** [comment]
Please review https://dev.cfengine.com/issues/5414 since the SUSE maintainer has kindly written the systemd init and identified some issues already.  @kkaempf is it OK to use the same init scripts for both cases, minimizing the maintenance work for both sides?

**Comment by bahamat** [comment]
I agree. We should reuse that one if possible. Is it or will it be included with core?

**Comment by tzz** [comment]
It is in master but not 3.6.x.  Also it lives in `contrib` which is not distributed with the packages.  So for the 3.6.0 release it will need to be manually included and used by the Debian and SUSE maintainers, but can come from that authoritative place so we have just one version.

**Comment by kkaempf** [comment]
@tzz the .service scripts should be systemd-specific, not SUSE-specific. I hope we can make them generic and cross-distribution

**Comment by tzz** [comment]
What functional testing is needed on Debian for systemd support?
- cf-execd
- cf-serverd
- what systemctl modes should be supported?  For instance `reload config` doesn't make sense since the cf daemons reload their own configs whenever they notice file changes.

**Comment by bahamat** [comment]
I think we just need to make sure that cf-execd, cf-serverd, and cf-monitord can start up and shut down.

Reload should probably either be a nop or aliased to restarting since there's no real notion of re-reading the config.

**Comment by tzz** [comment]
please watch and add your vote to https://dev.cfengine.com/issues/5243

**Comment by bahamat** [comment]
I can log in, but I get 403 trying to access that issue. I seem to be able to access other issues.

**Comment by tzz** [comment]
I've now made the ticket public, sorry about that.

**Comment by bahamat** [comment]
This has an upstream target of 3.7, so won't be available for Jessie.

We can patch in the following examples:
https://build.opensuse.org/package/view_file/systemsmanagement/cfengine/cf-serverd.service?expand=1
https://build.opensuse.org/package/view_file/systemsmanagement/cfengine/cf-execd.service?expand=1
https://build.opensuse.org/package/view_file/systemsmanagement/cfengine/cf-monitord.service?expand=1

**Comment by bahamat** [comment]
These are now included in upstream. They'll be pulled in during the next major release.
